In [1]:
"""
Created on Wed Oct 19 15:48:00 2018

@author: Daniel Cuesta, Alejandro Garo
"""

import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time

import queue

from sklearn.linear_model import LinearRegression

import networkx as nx

In [2]:
m_mg = np.random.binomial(3,0.5,(3,3))
print(m_mg)

[[1 0 2]
 [2 1 2]
 [3 0 1]]


In [3]:
# Ejercicio 1B: Agrandando nuestra ED
def m_mg_2_d_mg(m_mg):
    """
    De un multigrafo dirigido sin pesos, genera un diccionario de adyacencia a partir de su matriz de adyacencia.
    g[u]: diccionario de diccionarios con los nodos destino y el num de caminos con su peso (1 por ser unweighted)
    g[u][v]: num de caminos con su peso (1)
    Devuelve la matriz de adyacencia.

    Parámetros
    ----------
    m_mg: matriz de adyacencia, contiene el numero de caminos del nodo u al uv
    """
    for i in range(m_mg.shape[0]):
        d_mg[i] = {}
        for j in range(m_mg.shape[1]):
            d_mg[i][j] = {}
            for n_edge in range(m_mg[i][j]):
                d_mg[i][j].update({n_edge : 1})
    return d_mg

def rand_unweight_multigraph(n_nodes, num_max_multiple_edges = 3, prob = 0.5):
    """
    Genera un multigrafo dirigido sin pesos haciendo uso del metodo binomial del paquete random de numpy.
    Parámetros
    ----------
    n_nodes: numero de nodos
    num_max_multiple_edges: numero maximo de aristas de un nodo
    prob: probabilidad de generacion de las aristas
    """
    return np.random.binomial(num_max_multiple_edges, prob, (n_nodes,n_nodes))


def graph_2_multigraph(d_g):
    """
    Convierte un grafo que usa nuestra ED diccionario anterior a la nueva

    Parámetros
    ----------
    d_g: grafo usando la ED diccionario anterior
    """
    d_mg = {}
    for u in d_g.keys():
        d_mg.update({u : {}})
        # print(d_mg[u])
        #
        #
        #TODO saber si hay que meter caminos repetidos
        for v in d_g[u].keys():
            d_mg[u].update({v:{0:1}})
        # print(d_mg[u])
        # if d_mg[u][v] is v:
        #     d_mg[u].update({int(d_mg[u][v]) + 1 : 1})
        #     print(d_mg[u])
                
            
def print_multi_graph(d_mg):
    """
    Imprime el multigrafo dirigido sin pesos
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    for u in d_mg.keys():
        # print(d_mg[u])
        for v in d_mg[u].keys():
            l_w = []
            for w in d_mg[u][v].keys():
                l_w.append([d_mg[u][v][w]])
            print("(" + str(u) + "," + str(v) + ")" + ": " + str(l_w))

In [4]:
# Prueba

# m_mg a d_mg
# m_mg = rand_unweight_multigraph(3, num_max_multiple_edges = 3, prob = 0.5)
# d_mg = m_mg_2_d_mg(m_mg)
# print(m_mg)
# print_multi_graph(d_mg)

# d_g a d_mg
d_g = {
    0: {0: 1, 1: 1, 2: 1},
    1: {0:1, 2: 1},
    2: {3: 1},
    3: {1: 1}
}
graph_2_multigraph(d_g)

In [5]:
# Pruebas con NX MultiDiGraph
mg = nx.MultiDiGraph()

l_e = [(0,1,10), (0,2,1), (1,2,1), (2,3,1), (3,1,1)]

#mg.add_weighted_edges_from(l_e)
mg.add_weighted_edges_from(l_e)


print(mg[0])

print(mg[0][1])

{1: {0: {'weight': 10}}, 2: {0: {'weight': 1}}}
{0: {'weight': 10}}


In [6]:
# Ejercicio 2A: Detectando caminos eulerianos.

def adj_inc_directed_multigraph(d_mg):
    """
    Devuelve las adyacencias e incidencias de cada vertice del multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    inc = [0]*len(d_mg)
    adj = [0]*len(d_mg)
    for u in d_mg.keys():
        for v in d_mg[u].keys():
            #evitamos contar los ciclos en un mismo nodo
            if u != v:
                adj[u] = adj[u] + len(d_mg[u][v])
                inc[v] = inc[v] + len(d_mg[u][v])

    return (inc, adj)


In [7]:
m_mg = rand_unweight_multigraph(5, num_max_multiple_edges = 2, prob = 0.5)
d_mg = d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }
d_mg= m_mg_2_d_mg(m_mg)
print(m_mg, d_mg)
print_multi_graph(d_mg)
inc, adj = adj_inc_directed_multigraph(d_mg)
print(inc, adj)


[[0 0 1 1 2]
 [0 1 2 2 2]
 [2 1 0 1 0]
 [2 1 0 1 0]
 [0 0 2 0 1]] {0: {0: {}, 1: {}, 2: {0: 1}, 3: {0: 1}, 4: {0: 1, 1: 1}}, 1: {0: {}, 1: {0: 1}, 2: {0: 1, 1: 1}, 3: {0: 1, 1: 1}, 4: {0: 1, 1: 1}}, 2: {0: {0: 1, 1: 1}, 1: {0: 1}, 2: {}, 3: {0: 1}, 4: {}}, 3: {0: {0: 1, 1: 1}, 1: {0: 1}, 2: {}, 3: {0: 1}, 4: {}}, 4: {0: {}, 1: {}, 2: {0: 1, 1: 1}, 3: {}, 4: {0: 1}}, 5: {8: {0: 1}}, 6: {5: {0: 1}}, 7: {6: {0: 1}}, 8: {2: {0: 1}}, 9: {7: {0: 1}}}
(0,0): []
(0,1): []
(0,2): [[1]]
(0,3): [[1]]
(0,4): [[1], [1]]
(1,0): []
(1,1): [[1]]
(1,2): [[1], [1]]
(1,3): [[1], [1]]
(1,4): [[1], [1]]
(2,0): [[1], [1]]
(2,1): [[1]]
(2,2): []
(2,3): [[1]]
(2,4): []
(3,0): [[1], [1]]
(3,1): [[1]]
(3,2): []
(3,3): [[1]]
(3,4): []
(4,0): []
(4,1): []
(4,2): [[1], [1]]
(4,3): []
(4,4): [[1]]
(5,8): [[1]]
(6,5): [[1]]
(7,6): [[1]]
(8,2): [[1]]
(9,7): [[1]]
[4, 2, 6, 4, 4, 1, 1, 1, 1, 0] [4, 6, 4, 3, 2, 1, 1, 1, 1, 1]


In [8]:
def isthere_euler_path_directed_multigraph(d_mg):
    """
    Devuelve True o False segun haya o no un camino euleriano en el multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if sum(inc) != sum(adj):
        return False
    
    l = [adj_i - inc_i for adj_i, inc_i in zip(adj, inc)]
    k = 0
    for u in l:
        if u == 1:
            k+=1
        if u > 1 or u < -1 or (inc[u] == 0 and adj[u] == 0) or k == 2:
            return False
    
    return True


In [36]:
m_mg = rand_unweight_multigraph(5, num_max_multiple_edges = 1, prob = 0.5)
d_mg = d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }
# d_mg= m_mg_2_d_mg(m_mg)
print(d_mg)
print_multi_graph(d_mg)
inc, adj = adj_inc_directed_multigraph(d_mg)
print(inc, adj)
isthere_euler_path_directed_multigraph(d_mg)

{0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0: 1}}, 4: {9: {0: 1}}, 5: {8: {0: 1}}, 6: {5: {0: 1}}, 7: {6: {0: 1}}, 8: {2: {0: 1}}, 9: {7: {0: 1}}}
(0,1): [[1]]
(1,3): [[1]]
(2,0): [[1]]
(3,4): [[1]]
(4,9): [[1]]
(5,8): [[1]]
(6,5): [[1]]
(7,6): [[1]]
(8,2): [[1]]
(9,7): [[1]]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1] [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


True

In [37]:
def first_last_euler_path_directed_multigraph(d_mg):
    """
    Devuelve el punto inicial y el punto final del multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    first = []
    last = []
    
    if isthere_euler_path_directed_multigraph(d_mg) == False:
        return []
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    for u in range(len(inc)):
        if inc[u] - adj[u] > 0:
            last = u
        
        if inc[u] - adj[u] < 0:
            first = u
    
    if first == [] or last == []:
        first = 0
        last = 0
    
    return first, last

In [38]:
first_last_euler_path_directed_multigraph(d_mg)

(0, 0)

In [39]:
def euler_walk_directed_multigraph(u, d_mg):
    """
    Devuelve un camino euleriano del multigrafo d_mg
    
    Parámetros
    ----------
    u: vertice inicial
    d_mg: multigrafo usando la ED diccionario
    """
    
    cam_eu = [u]
    n_act = u
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if adj[u] == 0:
        return []

    for x in d_mg.keys():
        if n_act == x:
            for y in d_mg[x].keys():
                if n_act != y:
                    cam_eu.append(y)
                    if list(d_mg[x][y].keys()) != []:
                        k = list(d_mg[x][y].keys())[0]
                        del d_mg[x][y][k]
                        adj[x] = adj[x] - 1
                        inc[y] = inc[y] - 1
                        n_act = y
    return cam_eu
    
    

In [40]:
euler_walk_directed_multigraph(5,d_mg)

[5, 8, 2]

In [14]:
l_path = [5, 8, 2]
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {}, 6: {}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [15]:
def next_first_node(l_path, d_mg):
    """
    Devuelve el siguiente nodo del camino euleriano del multigrafo d_mg
    
    Parámetros
    ----------
    l_path: lista de nodos visitados
    d_mg: multigrafo usando la ED diccionario
    """
    
    u = l_path[-1]
    
    l_2 = euler_walk_directed_multigraph(u, d_mg)
    
    return l_2[1]
    
    

In [16]:
next_first_node(l_path, d_mg)

0

In [17]:
path_1 = [5, 8]
path_2 = [8, 2, 0, 1, 3, 4, 9, 7, 6]

In [18]:
def path_stitch(path_1, path_2):
    """
    Devuelve la union de las dos listas
    
    Parámetros
    ----------
    path1: lista de nodos 1
    path2: lista de nodos 2
    """    
    
    if path_1[-1] == path_2[0]:
        l_path = path_1
        l_path.pop(-1)
        for x in range(len(path_2)):
            l_path.append(path_2[x])
    else:
        l_path = path_2
        l_path.pop(-1)
        for x in range(len(path_1)):
            l_path.append(path_1[x])
    
    return l_path
    

In [19]:
path_stitch(path_1, path_2)

[5, 8, 2, 0, 1, 3, 4, 9, 7, 6]

In [20]:
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [21]:
def euler_path_directed_multigraph(d_mg):
    """
    Devuelve el camino del multigrafo d_mg
    
    Parámetros
    ----------
    l_path: lista de nodos visitados
    d_mg: multigrafo usando la ED diccionario
    """
    
    l_path = []
    
    for x in d_mg.keys():
        if l_path == []:
            l_path = euler_walk_directed_multigraph(x, d_mg)
            
        else:
            path_aux = euler_walk_directed_multigraph(x, d_mg)
            if path_aux != []:
                l_path = path_stitch(l_path, path_aux)
    
    return l_path
    

In [22]:
euler_path_directed_multigraph(d_mg)

[6, 5, 8, 2, 0, 1, 3, 4, 9, 7, 6]

In [23]:
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [24]:
def isthere_euler_circuit_directed_multigraph(d_mg):
    """
    Devuelve True o False segun haya o no un circuito euleriano en el multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    if isthere_euler_path_directed_multigraph == False:
        return False
    
    first, last = first_last_euler_path_directed_multigraph(d_mg)
    
    if first != last:
        return False
    
    return True


In [25]:
isthere_euler_circuit_directed_multigraph(d_mg)

True

In [26]:
def euler_circuit_directed_multigraph(d_mg, u=0):
    
    if isthere_euler_circuit_directed_multigraph == False:
        return
    
    cam_eu = [u]
    n_act = u
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if adj[u] == 0:
        return []
    while sum(inc) != 0:
        for x in d_mg.keys():
            if n_act == x:
                for y in d_mg[x].keys():
                    if n_act != y:
                        cam_eu.append(y)
                        if list(d_mg[x][y].keys()) != []:
                            k = list(d_mg[x][y].keys())[0]
                            del d_mg[x][y][k]
                            adj[x] = adj[x] - 1
                            inc[y] = inc[y] - 1
                            n_act = y
    return cam_eu
    

In [27]:
euler_circuit_directed_multigraph(d_mg, u=0)

[0, 1, 3, 4, 9, 7, 6, 5, 8, 2, 0]

In [157]:
# Ejercicio 3-A Secuenciación de lecturas

def random_sequence(len_seq):
    """
    Genera una secuencia aleatoria de longitud len_seq
    
    Parámetros
    ----------
    len_seq:longitud de la secuencia
    """
    seq = []
    elems_seq = ['A', 'C', 'G', 'T']
    for i in range(len_seq):
        seq.append(random.choice(elems_seq))
    return seq


def spectrum(sequence, len_read):
    """
    Genera un l-espectro a partir de la secuencia con tamaño de lectura len_read 
    Si el tamaño es incorrecto devuelve []

    Parámetros
    ----------
    sequence: secuencia
    len_read: tamaño de lectura
    """
    l_spectr = []
    lrandom_spectr = []
    i = 0
    # for i in range(len(sequence)):
    if len_read < 2:
        print("Tamaño de lectura incorrecta.")
        return []
    
    while(len(sequence[i : i + len_read : ]) == len_read):
        if sequence[i: i + len_read:] not in l_spectr:
            l_spectr.append(sequence[i: i + len_read:])
        # l_spectr.append(sequence[i: i + len_read:])
        i += 1
    # print("ESPECTRO ORDENADO: ", l_spectr)
    return random.sample(l_spectr, len(l_spectr))

def spectrum_2(spectr):
    """
    Genera un (l-1)-espectro a partir de un l-espectro
    Si el tamaño es incorrecto devuelve []
    Parámetros
    ----------
    spectr: l-espectro
    """
    if len(spectr[0]) < 2:
        print("Tamaño de espectro incorrecto")
        return []
    
    l1_spectr = []
    for sub_spectr in spectr:
        if sub_spectr[:len(sub_spectr) - 1] not in l1_spectr:
            l1_spectr.append(sub_spectr[:len(sub_spectr) - 1])
        if sub_spectr[1 : len(sub_spectr)] not in l1_spectr:
            l1_spectr.append(sub_spectr[1 : len(sub_spectr)])
    return l1_spectr

def spectrum_2_graph(spectr):
    """
    Genera el diccionario asociado a un espectro
    
    Parámetros
    ----------
    spectr: espectro
    """
    d_mg = {}
    n_paths = 0
    
    for sub_spectr in spectr:
        d_mg[spectr.index(sub_spectr)] = {}
        # print("Sub_spectr: ", sub_spectr)
        # print("D_MG1: ", d_mg)
        # print("Index: ", spectr.index(sub_spectr))
        for i, end_sub_spectr in enumerate(spectr):
            # Compruebo si hace ciclo:
            if i != d_mg[spectr.index(sub_spectr)]:
                if sub_spectr[1:] == end_sub_spectr[:len(end_sub_spectr) - 1]:
                    d_mg[spectr.index(sub_spectr)].update({spectr.index(end_sub_spectr) : {n_paths : 1}})
                    #print(spectr.index(sub_spectr))
                    #print(spectr.index(end_sub_spectr))
                    n_paths += 1
            n_paths = 0
        # if d_mg[spectr.index(sub_spectr)] == {}:
        #     print("Vacio")
    # print(d_mg)
    return d_mg

In [158]:
seq = random_sequence(5)
print("Secuencia")
print(seq)

l_spectr = spectrum(seq, 3)
print("Espectro l")
print(l_spectr)

l1_spectr = spectrum_2(l_spectr)
print("Espectro l-1")
print(l1_spectr)

d_mg = spectrum_2_graph(l_spectr)
d1_mg = spectrum_2_graph(l1_spectr)
print("Dicts")
print(d_mg, "\n", d1_mg)

Secuencia
['C', 'C', 'G', 'A', 'A']
Espectro l
[['G', 'A', 'A'], ['C', 'C', 'G'], ['C', 'G', 'A']]
Espectro l-1
[['G', 'A'], ['A', 'A'], ['C', 'C'], ['C', 'G']]
Dicts
{0: {}, 1: {2: {0: 1}}, 2: {0: {0: 1}}} 
 {0: {1: {0: 1}}, 1: {1: {0: 1}}, 2: {2: {0: 1}, 3: {0: 1}}, 3: {0: {0: 1}}}


In [128]:
# Ejercicio 3-B Todo junto

def check_sequencing(len_seq, len_read, l_spectr = []):
    """
    Construye un espectro con lecturas de tamaño len_read y su camino euleriano.
    Si no tuviera camino euleriano, lo devuelve como []
    Devuelve el camino y el espectro.
    Parámetros
    ----------
    len_seq: longitud de la secuencia
    len_read: longitud de las lecturas
    """
    if l_spectr == []:
        # Genero la secuencia
        seq = random_sequence(len_seq)
        print("Secuencia")
        print(seq)
        # Genero los espectros
        l_spectr = spectrum(seq, len_read)
        # print("Espectro desordenado")
        # print(l_spectr)

    # Las convierto a dict y busco el camino euleriano
    dg_mg_spectr = spectrum_2_graph(l_spectr)
    # print("Dicts")
    # print(dg_mg_spectr)
    
    # Check de las adyacencias e incidencias
    inc, adj = adj_inc_directed_multigraph(dg_mg_spectr)
    # print(inc, adj)
    dg_mg_u= first_last_euler_path_directed_multigraph(dg_mg_spectr)    
    # print("Nodo inicial y final:")
    # print(dg_mg_u)
    if dg_mg_u != []:
        for i in range(len(adj)):
            if i == dg_mg_u[0]:           # Nodo inicial, inc[0] = adj[0] - 1
                if inc[i] != adj[i] - 1:
                    print("La incidencia del nodo inicial tiene que ser la adyacencia del nodo inicial - 1")
                    return [], l_spectr 
            elif i == dg_mg_u[1]:
                if inc[i] != adj[i] + 1:          # Nodo final, inc[last] = adj[last] + 1
                    print("La incidencia del nodo final tiene que ser la adyacencia del nodo final + 1")
                    return [], l_spectr
            else:
                if inc[i] != adj[i]:
                    print("Los nodos intermedios tienen que tener adyacencias e incidencias iguales")
                    return [], l_spectr
    else:
        print("No hay camino euleriano")
        return [], l_spectr

    # Obtencion del EP
    ep_seq = euler_path_directed_multigraph(dg_mg_spectr)
    print("Camino euleriano de seq: " + str(ep_seq))
    
    return ep_seq, l_spectr
        
def path_2_sequence(l_path, spectrum_2):
    """
    Reconstruye una secuencia dado un camino euleriano y su espectro
    Devuelve el camino y el espectro, en caso de no existir camino euleriano 
    o fallo en la longitud de las lecturas, devuelve []
    
    Parámetros
    ----------
    l_path: camino
    spectrum_2: espectro
    """
    
    if l_path is []:
        print("No existe camino euleriano para este espectro.")
        return []
    
    # print(l_path, spectrum_2)
    if len(spectrum_2[0]) < 2:
        print("Tamaño de secuencia incorrecta")
        return []
    
    # Las convierto a dict y busco el camino euleriano
    dg_mg_spectr = spectrum_2_graph(spectrum_2)
    # print("Dicts")
    # print(dg_mg_spectr)
    
    # Check de las adyacencias e incidencias
    inc, adj = adj_inc_directed_multigraph(dg_mg_spectr)
    # print(inc, adj)
    dg_mg_u = first_last_euler_path_directed_multigraph(dg_mg_spectr)    
    # print("Nodo inicial y final:")
    # print(dg_mg_u)
    if dg_mg_u != []:
        for i in range(len(adj)):
            if i == dg_mg_u[0]:           # Nodo inicial, inc[0] = adj[0] - 1
                if inc[i] != adj[i] - 1:
                    print("La incidencia del nodo inicial tiene que ser la adyacencia del nodo inicial - 1")
                    return [], l_spectr 
            elif i == dg_mg_u[1]:
                if inc[i] != adj[i] + 1:          # Nodo final, inc[last] = adj[last] + 1
                    print("La incidencia del nodo final tiene que ser la adyacencia del nodo final + 1")
                    return [], l_spectr
            else:
                if inc[i] != adj[i]:
                    print("Los nodos intermedios tienen que tener adyacencias e incidencias iguales")
                    return [], l_spectr
    else:
        print("No hay camino euleriano")
        return [], l_spectr

    # Obtencion del EP
    ep_seq = euler_path_directed_multigraph(dg_mg_spectr)
    print("Camino euleriano de seq: " + str(ep_seq))
    # Reconstruccion de la secuencia
    seq_rec_aux = [[]]*len(ep_seq)
    j = 0
    for i in ep_seq:
        # print(spectrum_2[i])
        if j == 0:
            seq_rec_aux[j] = spectrum_2[i]
        else:
            seq_rec_aux[j] = spectrum_2[i][len(spectrum_2[i]) -1:] 
        j += 1
    
    seq_rec = []
    for sublist in seq_rec_aux:
        for elem in sublist:
            seq_rec.append(elem)

    return seq_rec

In [153]:
seq = ['A', 'T', 'T', 'C', 'C', 'T', 'G', 'T', 'G', 'T']

l_spectr = [['C', 'C', 'T'], ['T', 'G', 'T'], ['G', 'T', 'G'], ['C', 'T', 'G'], ['T', 'C', 'C'], ['A', 'T', 'T'], ['T', 'T', 'C']]

# Check Sequencing
l_path = check_sequencing(len_seq = 10, len_read = 3, l_spectr = [])

seq = path_2_sequence(l_path[0], spectrum_2(l_path[1]))
print(seq)
# if l_path != None:
# Path 2 Seq
#     print("e_path ", l_path[0])
#     print("spectr ", l_path[1])
# seq = random_sequence(10)
# l_spectr = spectrum(seq, 3)
# d_g = spectrum_2_graph(l_spectr)
# e_path = euler_path_directed_multigraph(d_g)
# l1_spectr = spectrum_2(l_spectr)
    
# path_2_sequence(e_path, l1_spectr)

Secuencia
['T', 'T', 'G', 'G', 'A', 'C', 'T', 'T', 'T', 'T']
Camino euleriano de seq: [3, 0, 4, 0, 1, 5, 0, 6, 2, 1]
Camino euleriano de seq: [2, 3, 5, 0, 0, 1, 2, 4, 2, 4]
['G', 'A', 'C', 'T', 'T', 'T', 'G', 'A', 'G', 'A', 'G']


In [69]:
# 3C Cuestiones sobre reconstrucción de secuencias:
def estimate(len_read):
    # Fijado el valor de longitud de secuencia
    len_seq = 10

    # Construimos nuestra secuencia inicial
    seq = random_sequence(len_seq)
    
    # Conseguimos nuestro espectro
    spec = spectrum(seq, len_read)
    # print("Espectro: ", spec)
    d_g = spectrum_2_graph(spec)
    
    # Busco el camino euleriano
    # print(d_g)
    e_path = euler_path_directed_multigraph(d_g)
    # print(e_path)

    # Lo transformo en secuencia y compruebo si son iguales
    # De serlo, extraigo la informacion
    seq_rec = path_2_sequence(e_path, spec)
    # print(seq_rec)
    spec_rec = spectrum(seq_rec, len_read)
    l_results = [0,0]
    if seq == seq_rec:
        print("SEQ IGUALES")
        l_results[0] = 1 
    else:
        print(seq, seq_rec)
        print("SEQ NO IGUALES")

    if sorted(list(spec)) == sorted(list(spec_rec)):
        print("SPEC IGUALES")
        l_results[1] = 1 
    else:
        print("SPEC NO IGUALES")
    # print(l_results)
    return l_results


In [155]:
len_read = 3
len_read_fin = 10 - len_read

l_results = [0, 0]
# Iteramos sobre len_read
for i in range(len_read_fin):
    l_res = estimate(len_read)
    l_results[0] += l_res[0]
    l_results[1] += l_res[1]
    len_read += 1

print(l_results)

No hay camino euleriano
['G', 'C', 'A', 'A', 'C', 'T', 'A', 'A', 'T', 'G'] ([], [['C', 'C', 'T'], ['T', 'G', 'T'], ['G', 'T', 'G'], ['C', 'T', 'G'], ['T', 'C', 'C'], ['A', 'T', 'T'], ['T', 'T', 'C']])
SEQ NO IGUALES
SPEC NO IGUALES
Camino euleriano de seq: [0, 1, 2, 5, 3, 6, 4]
SEQ IGUALES
SPEC IGUALES
Camino euleriano de seq: [3, 2, 4, 1, 0, 5]
SEQ IGUALES
SPEC IGUALES
Camino euleriano de seq: [0, 1, 4, 3, 2]
SEQ IGUALES
SPEC IGUALES
Camino euleriano de seq: [1, 0, 2, 3]
SEQ IGUALES
SPEC IGUALES
Camino euleriano de seq: [0, 2, 1]
SEQ IGUALES
SPEC IGUALES
Camino euleriano de seq: [1, 0]
SEQ IGUALES
SPEC IGUALES
[6, 6]


In [156]:
    print("\ncomprobamos cálculos de espectros y grafos sobre secuencias sencillas ..........")
    #seq = "ACGT"
    seq = random_sequence(4)
    print(seq)
    spec = spectrum(seq, len_read=3)
    print(spec)
    spec_2 = spectrum_2(spec)
    print(spec_2)
    d_g = spectrum_2_graph(spec)
    print(d_g)
    
    _ = input("pulsar Intro para continuar ....................\n")

    print("comprobamos reconstrucción ..........")
    # generamos secuencia aleatoria y calculamos espectro y grafo
    len_seq = 100 + np.random.randint(50)
    len_read = 3
    print("len_seq", len_seq,  "len_read", len_read, '\n')
    
    seq = random_sequence(len_seq)
    spec = spectrum(seq, len_read)
    d_g  = spectrum_2_graph(spec)
   
    # buscamos circuito euleriano y reconstruimos cadenas 
    e_path = euler_path_directed_multigraph(d_g)
    spec_2 = spectrum_2(spec)
    seq_rec = path_2_sequence(e_path, spec_2)
    print('\t'+str(seq)+'\n', '\t'+str(seq_rec)+'\n')
    
    # comprobamos coherencia de la reconstrucción
    spec_rec = spectrum(seq_rec, len_read)
    print("seq  iguales?", seq == seq_rec)
    print("spec iguales?", sorted(list(spec)) == sorted(list(spec_rec)))
    
    _ = input("pulsar Intro para continuar ....................\n")
    
    len_seq = 100 + np.random.randint(50)
    len_read = np.random.randint(10, 50)
    print("len_seq", len_seq,  "len_read", len_read, '\n')

    seq = random_sequence(len_seq)    
    spec = spectrum(seq, len_read)
    d_g  = spectrum_2_graph(spec)
    
    # buscamos circuito euleriano y reconstruimos cadenas 
    e_path = euler_path_directed_multigraph(d_g)
    spec_2 = spectrum_2(spec)
    seq_rec = path_2_sequence(e_path, spec_2)
    print('\t'+str(seq)+'\n', '\t'+str(seq_rec)+'\n')
    
    # comprobamos coherencia de la reconstrucción
    spec_rec = spectrum(seq_rec, len_read)
    print("seq  iguales?", seq == seq_rec)
    print("spec iguales?", sorted(list(spec)) == sorted(list(spec_rec)))
    


comprobamos cálculos de espectros y grafos sobre secuencias sencillas ..........
['T', 'G', 'G', 'C']
[['G', 'G', 'C'], ['T', 'G', 'G']]
[['G', 'G'], ['G', 'C'], ['T', 'G']]
{0: {}, 1: {0: {0: 1}}}
pulsar Intro para continuar ....................

comprobamos reconstrucción ..........
len_seq 136 len_read 3 

La incidencia del nodo inicial tiene que ser la adyacencia del nodo inicial - 1
	['A', 'A', 'A', 'G', 'C', 'G', 'G', 'A', 'G', 'T', 'A', 'T', 'A', 'T', 'C', 'G', 'A', 'T', 'C', 'A', 'A', 'T', 'C', 'G', 'A', 'G', 'G', 'C', 'T', 'G', 'G', 'A', 'A', 'C', 'G', 'C', 'A', 'G', 'G', 'G', 'G', 'G', 'G', 'C', 'C', 'C', 'A', 'C', 'A', 'G', 'G', 'T', 'T', 'T', 'C', 'T', 'C', 'A', 'T', 'G', 'G', 'G', 'C', 'A', 'G', 'C', 'C', 'G', 'T', 'T', 'G', 'G', 'A', 'G', 'A', 'T', 'C', 'A', 'T', 'C', 'T', 'C', 'A', 'T', 'C', 'A', 'A', 'A', 'T', 'G', 'C', 'C', 'A', 'T', 'A', 'G', 'C', 'G', 'A', 'G', 'A', 'A', 'T', 'A', 'G', 'C', 'C', 'A', 'A', 'T', 'G', 'G', 'A', 'T', 'G', 'G', 'T', 'G', 'G', 'T', 'T', '