In [1]:
"""
Created on Wed Oct 19 15:48:00 2018

@author: Daniel Cuesta, Alejandro Garo
"""

import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time

import queue

from sklearn.linear_model import LinearRegression

import networkx as nx

In [2]:
m_mg = np.random.binomial(3,0.5,(3,3))
print(m_mg)

[[1 1 0]
 [2 2 1]
 [2 3 2]]


In [3]:
# Ejercicio 1B: Agrandando nuestra ED
def m_mg_2_d_mg(m_mg):
    """
    De un multigrafo dirigido sin pesos, genera un diccionario de adyacencia a partir de su matriz de adyacencia.
    g[u]: diccionario de diccionarios con los nodos destino y el num de caminos con su peso (1 por ser unweighted)
    g[u][v]: num de caminos con su peso (1)
    Devuelve la matriz de adyacencia.

    Parámetros
    ----------
    m_mg: matriz de adyacencia, contiene el numero de caminos del nodo u al uv
    """
    d_mg = {}
    
    for i in range(m_mg.shape[0]):
        d_mg[i] = {}
        for j in range(m_mg.shape[1]):
            d_mg[i][j] = {}
            for n_edge in range(m_mg[i][j]):
                d_mg[i][j].update({n_edge : 1})
    return d_mg

def rand_unweight_multigraph(n_nodes, num_max_multiple_edges = 3, prob = 0.5):
    """
    Genera un multigrafo dirigido sin pesos haciendo uso del metodo binomial del paquete random de numpy.
    Parámetros
    ----------
    n_nodes: numero de nodos
    num_max_multiple_edges: numero maximo de aristas de un nodo
    prob: probabilidad de generacion de las aristas
    """
    return np.random.binomial(num_max_multiple_edges, prob, (n_nodes,n_nodes))


def graph_2_multigraph(d_g):
    """
    Convierte un grafo que usa nuestra ED diccionario anterior a la nueva

    Parámetros
    ----------
    d_g: grafo usando la ED diccionario anterior
    """
    d_mg = {}
    for u in d_g.keys():
        d_mg.update({u : {}})
        # print(d_mg[u])
        #
        #
        #TODO saber si hay que meter caminos repetidos
        for v in d_g[u].keys():
            d_mg[u].update({v:{0:1}})
        print(d_mg[u])
        # if d_mg[u][v] is v:
        #     d_mg[u].update({int(d_mg[u][v]) + 1 : 1})
        #     print(d_mg[u])
                
            
def print_multi_graph(d_mg):
    """
    Imprime el multigrafo dirigido sin pesos
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    for u in d_mg.keys():
        # print(d_mg[u])
        for v in d_mg[u].keys():
            l_w = []
            for w in d_mg[u][v].keys():
                l_w.append([d_mg[u][v][w]])
            print("(" + str(u) + "," + str(v) + ")" + ": " + str(l_w))

In [4]:
# Prueba

# m_mg a d_mg
# m_mg = rand_unweight_multigraph(3, num_max_multiple_edges = 3, prob = 0.5)
# d_mg = m_mg_2_d_mg(m_mg)
# print(m_mg)
# print_multi_graph(d_mg)

# d_g a d_mg
d_g = {
    0: {0: 1, 1: 1, 2: 1},
    1: {0:1, 2: 1},
    2: {3: 1},
    3: {1: 1}
}
graph_2_multigraph(d_g)

{0: {0: 1}, 1: {0: 1}, 2: {0: 1}}
{0: {0: 1}, 2: {0: 1}}
{3: {0: 1}}
{1: {0: 1}}


In [5]:
# Pruebas con NX MultiDiGraph
mg = nx.MultiDiGraph()

l_e = [(0,1,10), (0,2,1), (1,2,1), (2,3,1), (3,1,1)]

#mg.add_weighted_edges_from(l_e)
mg.add_weighted_edges_from(l_e)


print(mg[0])

print(mg[0][1])

{1: {0: {'weight': 10}}, 2: {0: {'weight': 1}}}
{0: {'weight': 10}}


In [6]:
# Ejercicio 2A: Detectando caminos eulerianos.

def adj_inc_directed_multigraph(d_mg):
    """
    Devuelve las adyacencias e incidencias de cada vertice del multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    inc = [0]*len(d_mg)
    adj = [0]*len(d_mg)
    for u in d_mg.keys():
        for v in d_mg[u].keys():
            #evitamos contar los ciclos en un mismo nodo
            if u != v:
                adj[u] = adj[u] + len(d_mg[u][v])
                inc[v] = inc[v] + len(d_mg[u][v])

    return (inc, adj)


In [7]:
m_mg = rand_unweight_multigraph(5, num_max_multiple_edges = 3, prob = 0.5)
d_mg = d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }
#m_mg_2_d_mg(m_mg)
print(m_mg)
print_multi_graph(d_mg)
inc, adj = adj_inc_directed_multigraph(d_mg)
print(inc, adj)


[[2 0 1 3 0]
 [2 2 1 1 0]
 [2 3 1 1 1]
 [2 2 1 2 1]
 [1 2 2 2 3]]
(0,1): [[1]]
(1,3): [[1]]
(2,0): [[1]]
(3,4): [[1]]
(4,9): [[1]]
(5,8): [[1]]
(6,5): [[1]]
(7,6): [[1]]
(8,2): [[1]]
(9,7): [[1]]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1] [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [8]:
def isthere_euler_path_directed_multigraph(d_mg):
    """
    Devuelve True o False segun haya o no un camino euleriano en el multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if sum(inc) != sum(adj):
        return False
    
    l = [adj_i - inc_i for adj_i, inc_i in zip(adj, inc)]
    k = 0
    for u in l:
        if u == 1:
            k+=1
        if u > 1 or u < -1 or (inc[u] == 0 and adj[u] == 0) or k == 2:
            return False
    
    return True


In [9]:
isthere_euler_path_directed_multigraph(d_mg)

True

In [10]:
def first_last_euler_path_directed_multigraph(d_mg):
    """
    Devuelve el punto inicial y el punto final del multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    first = []
    last = []
    
    if isthere_euler_path_directed_multigraph(d_mg) == False:
        return []
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    for u in range(len(inc)):
        if inc[u] - adj[u] > 0:
            last = u
        
        if inc[u] - adj[u] < 0:
            first = u
    
    if first == [] or last == []:
        first = 0
        last = 0
    
    return first, last

In [11]:
first_last_euler_path_directed_multigraph(d_mg)

(0, 0)

In [12]:
def euler_walk_directed_multigraph(u, d_mg):
    """
    Devuelve un camino euleriano del multigrafo d_mg
    
    Parámetros
    ----------
    u: vertice inicial
    d_mg: multigrafo usando la ED diccionario
    """
    
    cam_eu = [u]
    n_act = u
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if adj[u] == 0:
        return []
    
    for x in d_mg.keys():
        if n_act == x:
            adj[x] = adj[x] - 1
            for y in d_mg[x].keys():
                if n_act != y:
                    inc[y] = inc[y] - 1
                    cam_eu.append(y)
                    k = list(d_mg[x][y].keys())[0]
                    del d_mg[x][y][k]
                    n_act = y
    return cam_eu
    
    

In [13]:
euler_walk_directed_multigraph(5,d_mg)

[5, 8, 2]

In [14]:
l_path = [5, 8, 2]
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {}, 6: {}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [15]:
def next_first_node(l_path, d_mg):
    """
    Devuelve el siguiente nodo del camino euleriano del multigrafo d_mg
    
    Parámetros
    ----------
    l_path: lista de nodos visitados
    d_mg: multigrafo usando la ED diccionario
    """
    
    u = l_path[-1]
    
    l_2 = euler_walk_directed_multigraph(u, d_mg)
    
    return l_2[1]
    
    

In [16]:
next_first_node(l_path, d_mg)

0

In [17]:
path_1 = [5, 8]
path_2 = [8, 2, 0, 1, 3, 4, 9, 7, 6]

In [18]:
def path_stitch(path_1, path_2):
    """
    Devuelve la union de las dos listas
    
    Parámetros
    ----------
    path1: lista de nodos 1
    path2: lista de nodos 2
    """    
    
    if path_1[-1] == path_2[0]:
        l_path = path_1
        l_path.pop(-1)
        for x in range(len(path_2)):
            l_path.append(path_2[x])
    else:
        l_path = path_2
        l_path.pop(-1)
        for x in range(len(path_1)):
            l_path.append(path_1[x])
    
    return l_path
    

In [19]:
path_stitch(path_1, path_2)

[5, 8, 2, 0, 1, 3, 4, 9, 7, 6]

In [20]:
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [21]:
def euler_path_directed_multigraph(d_mg):
    """
    Devuelve el camino del multigrafo d_mg
    
    Parámetros
    ----------
    l_path: lista de nodos visitados
    d_mg: multigrafo usando la ED diccionario
    """
    
    l_path = []
    
    for x in d_mg.keys():
        if l_path == []:
            l_path = euler_walk_directed_multigraph(x, d_mg)
            
        else:
            path_aux = euler_walk_directed_multigraph(x, d_mg)
            if path_aux != []:
                l_path = path_stitch(l_path, path_aux)
    
    return l_path
    

In [22]:
euler_path_directed_multigraph(d_mg)

[6, 5, 8, 2, 0, 1, 3, 4, 9, 7, 6]

In [23]:
d_mg = { 0: {1: {0: 1}}, 1: {3: {0: 1}}, 2: {0: {0: 1}}, 3: {4: {0:1}}, 4: {9: {0:1}}, 5: {8: {0:1}}, 6: {5: {0:1}}, 7: {6: {0:1}}, 8: {2: {0:1}}, 9: {7: {0:1}} }

In [24]:
def isthere_euler_circuit_directed_multigraph(d_mg):
    """
    Devuelve True o False segun haya o no un circuito euleriano en el multigrafo d_mg
    
    Parámetros
    ----------
    d_mg: multigrafo usando la ED diccionario
    """
    
    if isthere_euler_path_directed_multigraph == False:
        return False
    
    first, last = first_last_euler_path_directed_multigraph(d_mg)
    
    if first != last:
        return False
    
    return True


In [25]:
isthere_euler_circuit_directed_multigraph(d_mg)

True

In [26]:
def euler_circuit_directed_multigraph(d_mg, u=0):
    
    if isthere_euler_circuit_directed_multigraph == False:
        return
    
    cam_eu = [u]
    n_act = u
    
    inc, adj = adj_inc_directed_multigraph(d_mg)
    
    if adj[u] == 0:
        return []
    while sum(inc) != 0:
        for x in d_mg.keys():
            if n_act == x:
                adj[x] = adj[x] - 1
                for y in d_mg[x].keys():
                    if n_act != y:
                        inc[y] = inc[y] - 1
                        cam_eu.append(y)
                        k = list(d_mg[x][y].keys())[0]
                        del d_mg[x][y][k]
                        n_act = y
    return cam_eu
    

In [27]:
euler_circuit_directed_multigraph(d_mg, u=0)

[0, 1, 3, 4, 9, 7, 6, 5, 8, 2, 0]

In [255]:
# Ejercicio 3-A Secuenciación de lecturas

def random_sequence(len_seq):
    seq = []
    elems_seq = ['A', 'C', 'G', 'T']
    for i in range(len_seq):
        seq.append(random.choice(elems_seq))
    return seq


def spectrum(sequence, len_read):
    l_spectr = []
    lrandom_spectr = []
    i = 0
    # for i in range(len(sequence)):
    if len_read < 3:
        print("Tamaño de lectura incorrecta.")
        return []
    
    while(len(sequence[i : i + len_read : ]) == len_read):
        if sequence[i: i + len_read:] not in l_spectr:
            l_spectr.append(sequence[i: i + len_read:])
        # l_spectr.append(sequence[i: i + len_read:])
        i += 1
    print("ESPECTRO ORDENADO: ", l_spectr)
    return random.sample(l_spectr, len(l_spectr))

def spectrum_2(spectr):
    l1_spectr = []
    for sub_spectr in spectr:
        if sub_spectr[:len(sub_spectr) - 1] not in l1_spectr:
            l1_spectr.append(sub_spectr[:len(sub_spectr) - 1])
        if sub_spectr[1 : len(sub_spectr)] not in l1_spectr:
            l1_spectr.append(sub_spectr[1 : len(sub_spectr)])
    return l1_spectr

def spectrum_2_graph(spectr):
    d_mg = {}
    n_paths = 0
    
    for sub_spectr in spectr:
        d_mg[spectr.index(sub_spectr)] = {}
        # print("Sub_spectr: ", sub_spectr)
        # print("D_MG1: ", d_mg)
        # print("Index: ", spectr.index(sub_spectr))
        for end_sub_spectr in spectr:
            if sub_spectr[1:] == end_sub_spectr[:len(end_sub_spectr) - 1]:
                d_mg[spectr.index(sub_spectr)].update({spectr.index(end_sub_spectr) : {n_paths : 1}})
                #print(spectr.index(sub_spectr))
                #print(spectr.index(end_sub_spectr))
                n_paths += 1
            n_paths = 0
    #print(d_mg)
    return d_mg

In [216]:
seq = random_sequence(10)
print("Secuencia")
print(seq)

l_spectr = spectrum(seq, 3)
print("Espectro l")
print(l_spectr)

l1_spectr = spectrum_2(l_spectr)
print("Espectro l-1")
print(l1_spectr)

d_mg = spectrum_2_graph(l_spectr)
d1_mg = spectrum_2_graph(l1_spectr)
print("Dicts")
print(d_mg, "\n", d1_mg)

Secuencia
['C', 'A', 'T', 'G', 'T', 'A', 'G', 'C', 'A', 'A']
Espectro l
[['T', 'G', 'T'], ['C', 'A', 'T'], ['A', 'T', 'G'], ['G', 'T', 'A'], ['C', 'A', 'A'], ['G', 'C', 'A'], ['T', 'A', 'G'], ['A', 'G', 'C']]
Espectro l-1
[['T', 'G'], ['G', 'T'], ['C', 'A'], ['A', 'T'], ['T', 'A'], ['A', 'A'], ['G', 'C'], ['A', 'G']]
Dicts
{0: {3: {0: 1}}, 1: {2: {0: 1}}, 2: {0: {0: 1}}, 3: {6: {0: 1}}, 4: {}, 5: {1: {0: 1}, 4: {0: 1}}, 6: {7: {0: 1}}, 7: {5: {0: 1}}} 
 {0: {1: {0: 1}, 6: {0: 1}}, 1: {0: {0: 1}, 4: {0: 1}}, 2: {3: {0: 1}, 5: {0: 1}, 7: {0: 1}}, 3: {0: {0: 1}, 4: {0: 1}}, 4: {3: {0: 1}, 5: {0: 1}, 7: {0: 1}}, 5: {3: {0: 1}, 5: {0: 1}, 7: {0: 1}}, 6: {2: {0: 1}}, 7: {1: {0: 1}, 6: {0: 1}}}


In [839]:
# Ejercicio 3-B Todo junto

def check_sequencing(len_seq, len_read, l_spectr = []):
    if l_spectr == []:
        # Genero la secuencia
        seq = random_sequence(len_seq)
        print("Secuencia")
        print(seq)
        # Genero los espectros
        l_spectr = spectrum(seq, len_read)
        print("Espectro desordenado")
        print(l_spectr)

    # Las convierto a dict y busco el camino euleriano
    dg_mg_spectr = spectrum_2_graph(l_spectr)
    print("Dicts")
    print(dg_mg_spectr)
    # Check de las adyacencias e incidencias
    inc, adj = adj_inc_directed_multigraph(dg_mg_spectr)
    print(inc, adj)

    dg_mg_u= first_last_euler_path_directed_multigraph(dg_mg_spectr)    
    print("Nodo inicial y final:")
    print(dg_mg_u)
    if dg_mg_u != []:
        for i in range(len(adj)):
            if i == dg_mg_u[0]:           # Nodo inicial, inc[0] = adj[0] - 1
                if inc[i] != adj[i] - 1:
                    print("La incidencia del nodo inicial tiene que ser la adyacencia del nodo inicial - 1")
                    return
            elif i == dg_mg_u[1]:
                print()
                if inc[i] != adj[i] + 1:          # Nodo final, inc[last] = adj[last] + 1
                    print("La incidencia del nodo final tiene que ser la adyacencia del nodo final + 1")
                    return
            else:
                if inc[i] != adj[i]:
                    print("Los nodos intermedios tienen que tener adyacencias e incidencias iguales")
                    return
    else:
        print("No hay camino euleriano")
        return

    ep_seq = euler_path_directed_multigraph(dg_mg_spectr)
    print("Camino euleriano de seq: " + str(ep_seq))
     
    # Reconstruccion de la secuencia
    seq_rec = [[]]*len(ep_seq)
    j = 0
    for i in ep_seq:
        print(l_spectr[i])
        if j == 0:
            seq_rec[j] = l_spectr[i]
        else:
            seq_rec[j] = l_spectr[i][len(l_spectr[i]) -1:] 
        j += 1
    # l_spectr = [l_spectr[i] = val for i, val in enumerate(ep_seq)]
     
    print(seq_rec)
        
def path_2_sequence(l_path, spectrum_2):
    
    pass

In [841]:
seq = ['A', 'T', 'T', 'C', 'C', 'T', 'G', 'T', 'G', 'T']

l_spectr = [['C', 'C', 'T'], ['T', 'G', 'T'], ['G', 'T', 'G'], ['C', 'T', 'G'], ['T', 'C', 'C'], ['A', 'T', 'T'], ['T', 'T', 'C']]

check_sequencing(len_seq = 10, len_read = 3, l_spectr = [])

# e_path = euler_path_directed_multigraph()

Secuencia
['G', 'G', 'T', 'T', 'C', 'G', 'A', 'T', 'A', 'G']
ESPECTRO ORDENADO:  [['G', 'G', 'T'], ['G', 'T', 'T'], ['T', 'T', 'C'], ['T', 'C', 'G'], ['C', 'G', 'A'], ['G', 'A', 'T'], ['A', 'T', 'A'], ['T', 'A', 'G']]
Espectro desordenado
[['G', 'A', 'T'], ['A', 'T', 'A'], ['C', 'G', 'A'], ['T', 'C', 'G'], ['T', 'T', 'C'], ['G', 'T', 'T'], ['G', 'G', 'T'], ['T', 'A', 'G']]
Dicts
{0: {1: {0: 1}}, 1: {7: {0: 1}}, 2: {0: {0: 1}}, 3: {2: {0: 1}}, 4: {3: {0: 1}}, 5: {4: {0: 1}}, 6: {5: {0: 1}}, 7: {}}
[1, 1, 1, 1, 1, 1, 0, 1] [1, 1, 1, 1, 1, 1, 1, 0]
Nodo inicial y final:
(6, 7)

Camino euleriano de seq: [6, 5, 4, 3, 2, 0, 1, 7]
['G', 'G', 'T']
['G', 'T', 'T']
['T', 'T', 'C']
['T', 'C', 'G']
['C', 'G', 'A']
['G', 'A', 'T']
['A', 'T', 'A']
['T', 'A', 'G']
[['G', 'G', 'T'], ['T'], ['C'], ['G'], ['A'], ['T'], ['A'], ['G']]
