In [2]:
"""
Created on Wed Oct 19 15:48:00 2018

@author: Daniel Cuesta, Alejandro Garo
"""

import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time

import queue

from sklearn.linear_model import LinearRegression

import networkx as nx

In [71]:
m_mg = np.random.binomial(3,0.5,(5,5))
print(m_mg)

[[1 0 2 3 0]
 [2 0 1 3 2]
 [3 3 1 1 0]
 [0 3 1 1 1]
 [1 2 2 1 0]]


In [76]:
def m_mg_2_d_mg(m_mg):
    
    d_mg = {}
    
    for i in range(m_mg.shape[0]):
        d_mg[i] = {}
        print(m_mg[i])
        for j in range(m_mg.shape[1]):
            d_mg[i][j] = {}
            for k in m_mg[i]:
                if k != 0:
                    print(k)
                    for val in range(k):
                        d_mg[i][j][val] = 1
    print(d_mg)

      
def rand_unweight_multigraph(n_nodes, num_max_multiple_edges = 3, prob = 0.5):
    
   np.random.binomial(num_max_multiple_edges, prob, (n_nodes,n_nodes))
    

In [77]:
m_mg_2_d_mg(m_mg)

[1 0 2 3 0]
1
2
3
1
2
3
1
2
3
1
2
3
1
2
3
[2 0 1 3 2]
2
1
3
2
2
1
3
2
2
1
3
2
2
1
3
2
2
1
3
2
[3 3 1 1 0]
3
3
1
1
3
3
1
1
3
3
1
1
3
3
1
1
3
3
1
1
[0 3 1 1 1]
3
1
1
1
3
1
1
1
3
1
1
1
3
1
1
1
3
1
1
1
[1 2 2 1 0]
1
2
2
1
1
2
2
1
1
2
2
1
1
2
2
1
1
2
2
1
{0: {0: {0: 1, 1: 1, 2: 1}, 1: {0: 1, 1: 1, 2: 1}, 2: {0: 1, 1: 1, 2: 1}, 3: {0: 1, 1: 1, 2: 1}, 4: {0: 1, 1: 1, 2: 1}}, 1: {0: {0: 1, 1: 1, 2: 1}, 1: {0: 1, 1: 1, 2: 1}, 2: {0: 1, 1: 1, 2: 1}, 3: {0: 1, 1: 1, 2: 1}, 4: {0: 1, 1: 1, 2: 1}}, 2: {0: {0: 1, 1: 1, 2: 1}, 1: {0: 1, 1: 1, 2: 1}, 2: {0: 1, 1: 1, 2: 1}, 3: {0: 1, 1: 1, 2: 1}, 4: {0: 1, 1: 1, 2: 1}}, 3: {0: {0: 1, 1: 1, 2: 1}, 1: {0: 1, 1: 1, 2: 1}, 2: {0: 1, 1: 1, 2: 1}, 3: {0: 1, 1: 1, 2: 1}, 4: {0: 1, 1: 1, 2: 1}}, 4: {0: {0: 1, 1: 1}, 1: {0: 1, 1: 1}, 2: {0: 1, 1: 1}, 3: {0: 1, 1: 1}, 4: {0: 1, 1: 1}}}
