In [2]:
"""
Created on Wed Oct 19 15:48:00 2018

@author: Daniel Cuesta, Alejandro Garo
"""

import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time
import math
import cmath

from cmath import pi
from cmath import exp

In [3]:
def swap(t, i, j):
    aux = t[i]
    t[i] = t[j]
    t[j] = aux

In [30]:
def split(t, ini, fin):
    """
    Reparte los elementos utilizando como pivote el primer elemento
    
    Parametros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    """
    pivote = t[ini]
    m = ini
                   
    for i in range(ini+1, fin+1):
        if t[i] < pivote :
            m +=1
            swap(t, i, m)

    swap(t, ini, m)

    return m
            

In [31]:
t =np.array([3,5,1,2,4])
print(split(t, 0, 4))
print(t)

2
[2 1 3 5 4]


In [108]:
def split_pivot(t, ini, fin, pivot=None):
    """
    Reparte los elementos utilizando como pivote el elemento en la posicion pivot
    
    Parametros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    """
    if (pivot == None):
        pivote = t[ini]
    else:
        pivote = t[pivot]

    swap(t, ini, pivot)
    m = ini

    for i in range(ini+1, fin+1):
        if t[i] < pivote :
            m +=1
            swap(t, i, m)

    swap(t, ini, m)
    print("m:", m)
    return m
    

In [109]:
t =np.array([3,5,1,2,4])
print(split_pivot(t, 0, 4, 0))
print(t)

m: 2
2
[2 1 3 5 4]


In [116]:
def qselect(t, ini, fin, ind, pivot=None):
    """
    Selecciona el elemento de la posicion definida por ind.

    Parámetros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    ind : indice de la tabla 
    """
    if ini > ind or ind > fin:
        return

    m = split_pivot(t, ini, fin, ind)

    if ind == m:
        return t[m], m
    elif ind < m:
        return qselect(t, ini, m-1, ind)
    else:
        return qselect(t, m+1, fin, ind)

In [129]:
t =np.array([3,5,1,2,4])
print(qselect(t, 0, 4, 0))
print(t)

m: 2
m: 1
m: 0
(1, 0)
[1 2 3 5 4]


In [140]:
len_list = np.random.randint(100, 151)

# random list: random shift + permutation
shf = np.random.randint(-len_list//2, len_list//2)
t = shf + np.random.permutation(len_list)
        
# random search limits
ini = np.random.randint(len_list//2)
fin = np.random.randint(len_list//2, len_list)
        
# random pos to search
pos = np.random.randint(fin-ini+1)


In [138]:
def qselect_sr(t, ini, fin, ind, pivot=None):
    """
    Selecciona el elemento de la posicion definida por ind sin recursion.

    Parámetros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    ind : indice de la tabla 
    """
    if ini > ind or ind > fin:
        return
    
    m = split_pivot(t, ini, fin, ind)
    
    while (ind!=m):
    
        m = split_pivot(t, ini, fin, ind)
        
        if ind < m:
            ini = ini
            fin = m-1
        else:
            ini = m+1
            fin = fin

    return t[m], m

In [141]:
print(t)
print(ini, fin, pos)
print(qselect_sr(t, ini, fin, pos))
print(t)

[ 14  23  20  45  46  92  26  54  63  65  -4   3  71  -3  93  41  53   1
   8  70  68  81   6  11   2  84  85  87  78  99  74  30  58  25  73  28
  88  18  90  43  10   0  86  34  96  98 101  97  38  17  77  62  94  59
  49  31  52  35  64  61 100  33  48   4  91  55  89  27   7  80  13  67
  22  12  19  50  44  39  51  47   9  57  24  66  29  69  95   5  37  -2
  21  32  42  15  60  72  75  83  56  -1  79  82  16  40  36  76]
1 87 58
m: 56
m: 69
m: 8
m: 60
m: 57
m: 58
(66, 58)
[ 14   4  -4   3  -3   1   2   0   5  45  46  41  53  26   8   6  11  54
  30  58  25  28  18  43  10  63  34  38  17  62  59  49  31  52  35  23
  61  33  48  20  55  27   7  13  22  12  19  50  44  39  51  47   9  57
  24  29  64  65  66  67  68  80  73  78  77  74  71  70  69  81  85  90
  96  98 101  97  87 100  91  99  94  92  93  89  84  86  95  88  37  -2
  21  32  42  15  60  72  75  83  56  -1  79  82  16  40  36  76]


In [27]:
def pivot_5(t, ini, fin):
    """
    Realiza la mediana de medianas de la tabla.

    Parámetros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    """
    ts = sorted(t)
    return (ts[ini]+ts[fin])//2

In [28]:
def qselect_5(t, ini, fin, pos):
    """
    Selecciona el elemento en posicion pos.

    Parámetros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    pos : elemento a buscar 
    """
    if ini > pos or pos > fin:
        return
    
    piv = pivot_5(t, ini, fin)
    sp = split_pivot(t, ini, fin, piv)
    
    while (pos!=sp):
        piv = pivot_5(t, ini, fin)
        sp = split_pivot(t, ini, fin, piv)

        if pos < sp:
            #ini = ini
            fin = sp-1
        else:
            ini = sp+1
            #fin = fin

    return t[sp], sp

In [29]:
def qsort_5(t, ini, fin):
    """
    Ordena la tabla.

    Parámetros
    ----------
    t : tabla
    ini : primer elemento
    fin : ultimo elemento
    """
    if ini > fin: 
        return None
    if ini == fin:
        return t
    
    else:
        piv = pivot_5(t, ini, fin)
        sp = split_pivot(t, ini, fin, piv)
        
        if ini < sp-1:
            if qsort_5(t, ini, sp-1).any() == None:
                return None
        
        if sp+1 < fin:
            if qsort_5(t, sp+1, fin).any() == None:
                return None
    return t