In [2]:
"""
Created on Wed Oct 19 15:48:00 2018

@author: Daniel Cuesta, Alejandro Garo
"""

import string, random
import numpy as np
import matplotlib.pyplot as plt
import sys
import time
import math
import cmath

from cmath import pi
from cmath import exp

In [3]:
def swap(t, i, j):
    aux = t[i]
    t[i] = t[j]
    t[j] = aux

In [30]:
def split(t, ini, fin):
    
    pivote = t[ini]
    m = ini
                   
    for i in range(ini+1, fin+1):
        if t[i] < pivote :
            m +=1
            swap(t, i, m)

    swap(t, ini, m)

    return m
            

In [31]:
t =np.array([3,5,1,2,4])
print(split(t, 0, 4))
print(t)

2
[2 1 3 5 4]


In [35]:
def split_pivot(t, ini, fin, pivot=None):
    if (pivot == None):
        pivote = t[ini]
    else:
        pivote = t[pivot]
        
    m = -1
    for i in range(0,len(t)-1):
        if t[i] == pivote:
            m = i
            break

    swap(t, ini, m)
    m = ini

    for i in range(ini+1, fin+1):
        if t[i] < pivote :
            m +=1
            swap(t, i, m)

    swap(t, ini, m)

    return m
    

In [53]:
t =np.array([3,5,1,2,4])
print(split_pivot(t, 0, 4))
print(t)

2
[2 1 3 5 4]


In [51]:
def qselect(t, ini, fin, ind, pivot=None):
    if ini > ind or ind > fin:
        return

    m = split_pivot(t, ini, fin)

    if ind == m:
        return t[m], m
    elif ind < m:
        return qselect(t, ini, m-1, ind)
    else:
        return qselect(t, m+1, fin, ind-(m-ini+1))

In [52]:
t =np.array([3,5,1,2,4])
print(qselect(t, 0, 4, 3))
print(t)

None
[2 1 3 5 4]


In [ ]:
def qselect_sr(t, ini, fin, ind, pivot=None):
    if ini > ind or ind > fin:
        return
    
    m = spllit_pivot(t, ini, fin, ind)
    

In [27]:
def pivot_5(t, ini, fin):
    ts = sorted(t)
    return (ts[ini]+ts[fin])//2

In [28]:
def qselect_5(t, ini, fin, pos):
    if ini > pos or pos > fin:
        return
    
    piv = pivot_5(t, ini, fin)
    sp = split_pivot(t, ini, fin, piv)
    
    if pos == sp:
        return t[sp], sp
    elif pos < sp:
        return qselect_5(t, ini, sp-1, pos)
    else:
        return qselect_5(t, sp+1, fin, pos)

In [29]:
def qsort_5(t, ini, fin):
    if ini > fin: 
        return None
    if ini == fin:
        return t
    
    else:
        piv = pivot_5(t, ini, fin)
        sp = split_pivot(t, ini, fin, piv)
        
        if ini < sp-1:
            if qsort_5(t, ini, sp-1).any() == None:
                return None
        
        if sp+1 < fin:
            if qsort_5(t, sp+1, fin).any() == None:
                return None
    return t